import { GameDrawerSurface } from './GameDrawerSurface';
import { t as tr, useLanguage } from '../i18n';
import { Text } from '../i18n/Text';
import React, { useState } from 'react';
import { StyleSheet, View, useWindowDimensions } from 'react-native';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import { LinearGradient } from '../components/LinearGradient';
import { gameFont } from '../gameTypography';
import { Icon, Pressable, ScrollView } from './components';

export function NumbersDrawer({ calls, onReplay, onClose, native = false }: { native?: boolean; calls: number[]; onReplay: (number: number) => void; onClose: () => void }) {
  useLanguage();
  const [mode, setMode] = useState<'board' | 'history'>('board'), { height } = useWindowDimensions();
  const current = calls.at(-1), seen = new Set(calls);
  return <GameDrawerSurface native={native} onClose={onClose}><SafeAreaProvider><View style={styles.overlay}><Pressable accessibilityRole="button" accessibilityLabel={tr("Close numbers overlay")} onPress={onClose} style={StyleSheet.absoluteFill} /><LinearGradient colors={['#fffbea', '#fff5d9', '#fffbea']} style={[styles.panel, { marginTop: height * .12 }]}><SafeAreaView accessibilityViewIsModal style={{ flex: 1 }} edges={['bottom']}><View style={styles.header}><Text style={styles.title}>{tr("Numbers")}</Text><Pressable accessibilityRole="button" accessibilityLabel={tr("Close numbers")} onPress={onClose} style={styles.close}><Icon name="close" color="#241034" size={23} /></Pressable></View>
    <View accessibilityRole="tablist" style={styles.tabs}>{(['board', 'history'] as const).map(tab => <Pressable key={tab} accessibilityRole="tab" accessibilityState={{ selected: mode === tab }} onPress={() => setMode(tab)} style={[styles.tab, mode === tab && styles.selectedTab]}><LinearGradient pointerEvents="none" colors={mode === tab ? ['#fff36a', '#ffd338', '#ffba22'] : ['#dfc7f3', '#b797d2']} style={StyleSheet.absoluteFill} /><Text style={styles.tabText}>{tab === 'board' ? tr("Board") : tr("History")}</Text></Pressable>)}</View>
    <ScrollView style={{ flex: 1 }} contentContainerStyle={styles.content}>
      {mode === 'board' ? <View accessibilityLabel={tr("{v0} called, {v1} left", { v0: calls.length, v1: 90 - calls.length })} style={styles.board}>{Array.from({ length: 9 }, (_, row) => <View key={row} style={{ flexDirection: 'row' }}>{Array.from({ length: 10 }, (_, column) => {
        const number = row * 10 + column + 1, called = seen.has(number), latest = number === current;
        return <Pressable key={number} accessibilityRole={called ? 'button' : 'text'} accessibilityLabel={`${number}, ${called ? latest ? tr('current number, replay') : tr('called, replay') : tr('not called')}`} disabled={!called} onPress={() => onReplay(number)} style={[styles.cell, { backgroundColor: called ? '#f32146' : '#fff5dd' }, latest && styles.current]}><Text maxFontSizeMultiplier={1} style={[styles.number, { color: called ? '#fff' : '#221921' }]}>{number}</Text></Pressable>;
      })}</View>)}</View> : <View style={{ gap: 6 }}>{!calls.length && <Text style={styles.empty}>{tr("Waiting for the first number")}</Text>}{[...calls].reverse().map((number, i) => <Pressable key={number} accessibilityRole="button" accessibilityLabel={tr("Call {v0}, number {v1}, replay", { v0: calls.length - i, v1: number })} onPress={() => onReplay(number)} style={styles.historyRow}><Text style={styles.order}>#{calls.length - i}</Text><RecentBall number={number} /><Text style={styles.historyText}>{i === 0 ? tr("Current number") : tr("Called number")}</Text><Icon name="sound" color="#6a329b" size={23} /></Pressable>)}</View>}
      {mode === 'board' && <View style={styles.recent}><View style={{ flex: 1, gap: 7 }}><Text style={styles.label}>{tr("Recent balls")}</Text><View style={{ flexDirection: 'row', gap: 5 }}>{calls.slice(-4).map(number => <Pressable accessibilityRole="button" accessibilityLabel={tr("Replay {v0}", { v0: number })} key={number} onPress={() => onReplay(number)}><RecentBall number={number} /></Pressable>)}</View>{!calls.length && <Text style={styles.empty}>{tr("Waiting for the first number")}</Text>}</View><View style={styles.replay}><Text style={styles.label}>{tr("Replay")}{' '}{current ?? '—'}</Text><Pressable accessibilityRole="button" accessibilityLabel={tr("Replay current number")} disabled={!current} onPress={() => { if (current) onReplay(current); }} style={styles.replayButton}><LinearGradient colors={['#f4e9ff', '#c4a2e9']} style={StyleSheet.absoluteFill} /><Icon name="play" color="#4c1884" size={25} /></Pressable></View></View>}
    </ScrollView></SafeAreaView></LinearGradient></View></SafeAreaProvider></GameDrawerSurface>;
}

function RecentBall({ number }: { number: number }) {
  useLanguage(); return <LinearGradient colors={['#ff5770', '#ff002e', '#de0021']} style={styles.ball}><View style={styles.ballShine} /><Text style={styles.ballNumber}>{number}</Text></LinearGradient>; }
const styles = StyleSheet.create({
  overlay: { flex: 1, backgroundColor: '#0e051c99', alignItems: 'center' }, panel: { width: '100%', maxWidth: 576, flex: 1, paddingHorizontal: 12, borderTopLeftRadius: 25, borderTopRightRadius: 25, overflow: 'hidden', borderTopWidth: 1, borderColor: '#fffef4' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: 10, paddingBottom: 11 }, title: { color: '#201038', fontFamily: gameFont.bold, fontSize: 28 }, close: { width: 36, height: 36, borderRadius: 21, borderWidth: .8, borderColor: '#d7c3a4', backgroundColor: '#fcf0d9', alignItems: 'center', justifyContent: 'center' },
  tabs: { flexDirection: 'row', height: 37, borderWidth: .8, borderColor: '#bda781', borderRadius: 11, overflow: 'hidden', marginBottom: 11 }, tab: { flex: 1, alignItems: 'center', justifyContent: 'center', overflow: 'hidden', borderRadius: 10 }, selectedTab: { borderWidth: 1, borderColor: '#eea61b', borderBottomWidth: 2 }, tabText: { color: '#281636', fontFamily: gameFont.medium, fontSize: 18 },
  content: { paddingBottom: 22 }, board: { borderRadius: 7, borderWidth: .6, borderColor: '#bfa982', overflow: 'hidden' }, cell: { flex: 1, aspectRatio: .81, borderWidth: .5, borderColor: '#d7c7a9', borderRadius: 6, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }, current: { borderWidth: 2.2, borderColor: '#ffce22' }, number: { fontFamily: gameFont.medium, fontSize: 15, includeFontPadding: false },
  recent: { flexDirection: 'row', marginTop: 15, paddingTop: 16, borderTopWidth: .7, borderColor: '#ceb998', gap: 8 }, label: { color: '#29123a', fontFamily: gameFont.medium, fontSize: 12 }, replay: { borderLeftWidth: .6, borderColor: '#c5a67f', paddingLeft: 13, gap: 5, alignItems: 'center' }, replayButton: { width: 37, height: 37, borderRadius: 20, borderWidth: 1, borderColor: '#ae81d3', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  ball: { width: 34, height: 38, borderRadius: 22, borderWidth: .8, borderColor: '#ff8b92', borderBottomWidth: 2, borderBottomColor: '#c52025', alignItems: 'center', justifyContent: 'center' }, ballShine: { position: 'absolute', top: 3, left: 5, right: 5, height: 13, borderTopWidth: 1.2, borderColor: '#ffccd3', borderRadius: 15 }, ballNumber: { color: '#fff', fontSize: 18, fontFamily: gameFont.medium, includeFontPadding: false }, historyRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 5, borderBottomWidth: .6, borderColor: '#e1cfaa' }, order: { width: 29, color: '#8c6c64', fontFamily: gameFont.medium, fontSize: 13 }, historyText: { color: '#432750', fontFamily: gameFont.medium, fontSize: 14, flex: 1 }, empty: { color: '#8c6c64', fontSize: 12, paddingVertical: 9 },
});
