// Build-time only. The app bundles WAVs; Piper and its models never ship in the APK.
import { writeFileSync, existsSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { callParts } from "../shared/callPhrase.ts";
const root = fileURLToPath(new URL("../", import.meta.url));
const localPython = path.join(
  root,
  ".tools",
  "voice-venv",
  process.platform === "win32" ? "Scripts/python.exe" : "bin/python",
);
const python =
  process.env.VOICE_PYTHON ||
  (existsSync(localPython) ? localPython : "python");
const phrases = Array.from({ length: 90 }, (_, i) => ({
  number: i + 1,
  ...callParts(i + 1),
}));
const result = spawnSync(
  python,
  [path.join(root, "scripts/generate-voice.py")],
  {
    cwd: root,
    input: JSON.stringify(phrases),
    stdio: ["pipe", "inherit", "inherit"],
  },
);
if (result.error) throw result.error;
if (result.status !== 0)
  throw new Error(
    "Voice generation failed. Install scripts/voice-requirements.txt in your Python environment.",
  );
const voices = [{ key: "female", folder: "en-female" }];
const entries = voices
  .map(
    (voice) =>
      "  " +
      voice.key +
      ": {\n" +
      phrases
        .map(({ number: n }) => {
          const base = "../assets/voice/" + voice.folder + "/" + n;
          return (
            "    " + n + ": { full: require('" + base + ".wav')" + "" + " },"
          );
        })
        .join("\n") +
      "\n  },",
  )
  .join("\n");
writeFileSync(
  path.join(root, "src/voiceBank.ts"),
  "// Generated by npm run voice:generate. Static requires embed offline neural speech.\n" +
    "import type { Announcement } from './announcementPlayer';\n" +
    "export const VOICE_BANK: Record<'female', Record<number, Announcement>> = {\n" +
    entries +
    "\n};\n",
);
